apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: stackrox-central-services
  namespace: stackrox
spec:
  central:
    customize:
      envVars:
        - name: ROX_DECLARATIVE_CONFIG_DIR
          value: "/run/stackrox.io/declarative-configuration"
    declarativeConfiguration:
      secrets:
        - name: openshift-auth-provider
    exposure:
      route:
        enabled: true
  scannerV4:
    scannerComponent: Default
  scanner:
    scannerComponent: Enabled
