apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: stackrox-central-services
  namespace: stackrox
spec:
  central:
    declarativeConfiguration:
      secrets:
        - name: openshift-auth-provider
    exposure:
      route:
        enabled: true
  scannerV4:
    scannerComponent: Default
  scanner:
    scannerComponent: Enabled
