apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- central.yaml

configMapGenerator:
- name: openshift-auth-provider
  namespace: stackrox
  files:
  - declarative-auth.yaml

patches:
- path: patch-central-resources.yaml
- path: patch-acs-nodeselector.yaml

generatorOptions:
  disableNameSuffixHash: false