apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../infrastructure/acs/base
  - central.yaml
  - secured-cluster.yaml

secretGenerator:
  - name: openshift-auth-provider
    namespace: stackrox
    files:
      - declarative-auth.yaml
    options:
      disableNameSuffixHash: true

patches:
  - path: patch-central-resources.yaml
  - path: patch-acs-nodeselector.yaml
