kind: SecuredCluster
apiVersion: platform.stackrox.io/v1alpha1
metadata:
  name: hub
  namespace: stackrox
spec:
  clusterName: hub
  admissionControl:
    replicas: 1
  collector:
    resources:
      requests:
        memory: 256Mi
        cpu: 256m
      limits:
        memory: 512Mi
        cpu: 512m
  sensor:
    resources:
      requests:
        memory: 256Mi
        cpu: 256m
      limits:
        memory: 512Mi
        cpu: 512m
