apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: cluster-gitops
  namespace: openshift-gitops
spec:
  applicationSet: {}
  server:
    route:
      enabled: true
  sso:
    provider: dex
    dex:
      openShiftOAuth: true
  rbac:
    policy: |
      g, cluster-admins, role:admin
      g, admins, role:admin
    defaultPolicy: "role:readonly"
  kustomizeBuildOptions: "--enable-helm"
